#!/usr/bin/bash

echo "Clearing VSCode cache..."
rm -rf /Users/phuc/Library/ApplicationSupport/Code/User/workspaceStorage/*
rm -rf /Users/phuc/Library/ApplicationSupport/Code/logs/*
rm -rf /Users/phuc/Library/ApplicationSupport/Code/Cache/*
rm -rf /Users/phuc/Library/ApplicationSupport/Code/CachedData/*
rm -rf /Users/phuc/Library/ApplicationSupport/Code/CachedExtensions/*
rm -rf /Users/phuc/Library/ApplicationSupport/Code/GPUCache/*

echo "Finshed clearing VSCode cache."

